const bookingData = {
  booking: tmpBooking,
  SpareTotal: spareTotal,
  ServiceTotal: serviceTotal,
  serviceCenterAddress: serviceCenterAddress,
  customerDetail: [
    { label: "Name : ", value: "Jatin 14ry" },
    {
      label: "Address : ",
      value: "Plot no.967 Bypass Road, Sector-9, Faridabad Haryana - 121006",
    },
    { label: "Contact : ", value: "9027914004" },
    { label: "Email ID : ", value: "account@pikpart.com" },
    { label: "GSTIN/UIN : ", value: "06AAICR7704D1ZI" },
    { label: "GST Address : ", value: "14RY Farm" },
    { label: "Business Name : ", value: "Choudhary" },
  ],
  vehicleDetail: [
    { label: "Vehicle Type : ", value: "4W" },
    {
      label: "Vehicle No. : ",
      value: "UP23AU1001",
    },
    { label: "Chassis No. : ", value: "xxxxxxxxxxxxx" },
    { label: "Engine No. : ", value: "xxxxxxxxxxxxx" },
    { label: "Brand/Model : ", value: "Naam hi Brand" },
    { label: "Fuel Type : ", value: "Petrol" },
    { label: "Odometer : ", value: "398394 kms" },
  ],
  serviceDetail: [
    { label: "Generated On : ", value: "28th Jul 2025" },
    {
      label: "Supervisor. : ",
      value: "Pawan Bhamniya",
    },
  ],
  tableHeader: [
    "Spare/Service Description",
    "Product Code",
    "HSN/SAC",
    "MRP",
    "Dis (₹)",
    "Quantity",
    "Value",
  ],
  tableColumnWidths: [180, 76, 76, 60, 45, 50, 73],
  bookingCheckpoints,
  totalAmountInWords: "Amount in words : ",
  amountInWords,
  termsAndConditions: [
    "All invoices are payable within the stipulated due date.",
    "Interest may apply on delayed payments as per company policy.",
    "Goods once sold are not eligible for return or exchange.",
    "Any shortage, damage, or discrepancy must be reported within 24 hours of delivery.",
    "Warranty/Guarantee, wherever applicable, will be governed by the manufacturer’s terms only.",
    "Prices, specification and availability are subject to change without prior notice.",
    "Company reserves the right to revise or cancel the invoice if required.",
    "All transactions are governed by applicable GST laws.",
    "Jurisdiction for all disputes shall be the city of our registered office only.",
    "E. & O.E. (Errors & Omissions Excepted).",
    "For any queries or document requirements related to this invoice, please email us at the address mentioned above.",
  ],
};

bookingCheckpoints.push({
  //   id,
  //   checkpointId,
  name,
  //   status,
  //   type,
  //   srNo,
  jobSheet,
  //   isServiced,
  //   amountTotal: amountTotal.toFixed(2),
  //   beforeImage,
  //   afterImage,
  //   beforeImages,
  //   beforeVideos,
  //   afterImages,
  //   afterVideos,
});

jobSheet.push({
  //   id,
  //   itemId,
  //   serviceId,
  //   driverInspection,
  name,
  count,
  price,
  type,
  discount,
  discountPercent,
  tax,
  discountedPrice,
  total,
  taxRate,
  //   status,
  //   customerApprovalStatus,
  //   categoryId,
  //   startEngineCc,
  //   endEngineCc,
  //   beforeImage,
  //   afterImage,
  //   beforeVideo,
  //   afterVideo,
  //   packageItems,
  //   beforeImages,
  //   beforeVideos,
  //   afterImages,
  //   afterVideos,
});
